// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PBandJ.Api.Entities;
using PBandJ.Api.Enums;
using System;

namespace PBandJ.Api.Migrations
{
    [DbContext(typeof(HandRangeContext))]
    [Migration("20171224033528_CreatePositionMenuEntity")]
    partial class CreatePositionMenuEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PBandJ.Api.Entities.HandRange", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("Position");

                    b.Property<string>("Hands");

                    b.HasKey("UserId", "Position");

                    b.ToTable("HandRanges");
                });

            modelBuilder.Entity("PBandJ.Api.Entities.PositionMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<int?>("ScenarioId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("PositionMenus");
                });

            modelBuilder.Entity("PBandJ.Api.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("PBandJ.Api.Entities.PositionMenu", b =>
                {
                    b.HasOne("PBandJ.Api.Entities.Scenario")
                        .WithMany("PositionMenus")
                        .HasForeignKey("ScenarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
